### PR TITLE
Start side panel styles

### PR DESCRIPTION
**Pull request by joehand**
Getting close. Current Status:

screen shot 2017-01-09 at 17 35 13

A few questions:
* The button looks different than the default btn style. Ya? (Right now its the default)
* What are those list items? Not sure what to style for the icons.
* Links - Should they be gray or green (default)?

Random notes/To Do's:
* I think the box shadow only happens on the gray part. Which is gonna make it less fun to implement because we cant use the main div to put the shadow on.
* Still need to finish the list items

TO DO:

- [x] Get list of Dats
- [x] Style list of Dats
- [x] Add link to manage your account (where does this go?)
- [x] Minimal box shadow (I did one on the entire element, but may look bad. Can screenshot that to review)

### CODE REVIEW

**Comment by karissa** [comment]
Let's have the list items for now be your dats. So this is like a profile pane, essentially, for now! You can get the dat list for the given user by doing `/api/v1/dats?user_id=<user_id>`

Button style will need revamped probably best in a separate PR, I wouldn't worry about it at the moment. 

I wouldn't worry about box shadow either, let's open a separate issue for that.

**Comment by joehand** [comment]
@karissa added a version with [this commit](https://github.com/datproject/datfolder/pull/356/commits/2c1961ff028c2b5e3c0c253da37d36570a1ad8a9). Very hacky but figure we need to get it into the state somehow and we'll use it in the user model for now.

But let me know if I should revert that commit!

**Comment by joehand** [comment]
Think I've done most of what I can do here for now! Main issue remaining (besides style things mentioned above) is what happens when the list gets long. We can do scrolling but wanted to get styles for that before I implemented.

Moving to the paged file list issue.

**Comment by Kriesse** [comment]
Nice!! Fixed the merge conflict. Would like to merge if no objections // @karissa

**Comment by karissa** [comment]
go for it!

**Comment by karissa** [comment]
Wait, there's a standard problem:

  /home/travis/build/datproject/datfolder/client/js/models/user.js:95:6: Unexpected trailing comma.

**Pull request merged**
